@extends('admin.admin_main')

@section('page-css')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@endsection

@section('content')
<div class="container-fluid">

    <div class="row mb-3">
        <div class="col-md-12">
            <h4 class="mb-0">
                <i class="fa fa-certificate"></i> Certificate Management Logs
            </h4>
        </div>
    </div>

    {{-- Student Info --}}
    <div class="card mb-3 shadow-sm">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <strong>Student Name:</strong><br>
                    {{ $enrolledCourse?->student?->name }}
                </div>
                <div class="col-md-4">
                    <strong>Course:</strong><br>
                    {{ $enrolledCourse->course->name ?? 'N/A' }}
                </div>
                <div class="col-md-4">
                    <strong>Total Fee:</strong><br>
                    {{ number_format($enrolledCourse->total_fee, 2) }}
                </div>
            </div>
        </div>
    </div>

    {{-- Certificate History --}}
    <div class="card shadow-sm">
        <div class="card-header">
            <strong>Certificate Generation Logs</strong>
        </div>

        <div class="card-body">
            <table class="table table-bordered table-striped" id="crm_certificates">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Generated By</th>
                        <th>Generated Count</th>
                        <th>Last Generated At</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($certificates as $index => $certificate)
                        <tr>
                            <td>{{ $index + 1 }}</td>
                            <td>{{ $certificate->user->name ?? 'System' }}</td>
                            <td>{{ $certificate->generated_count }}</td>
                            <td>
                                {{ $certificate->last_generated_at
                                    ? \App\Classes\LyskillsCarbon::parse($certificate->last_generated_at)->toDayDateTimeString()
                                    : 'N/A'
                                }}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

</div>
@endsection

@section('page-js')
<script>
    $(document).ready(function () {
        new simpleDatatables.DataTable("#crm_certificates", {
            searchable: true,
            perPage: 10
        });
    });
</script>
@endsection
